### ISSUE TITLE
Change "wtp" to "wingtip-dpt"

### ISSUE THREAD

**Issue by caligaris** [Microsoft/WingtipTicketsSaaS-DbPerTenant#10]
https://github.com/Microsoft/WingtipTicketsSaaS-DbPerTenant/blob/89d9fdee6980b2a3a04fe561afc02214d97760ab/Learning%20Modules/Provision%20and%20Catalog/Demo-ProvisionAndCatalog.ps1#L63

**Comment by AyoOlubeko** [comment]
Hi Luis. Thanks for letting us know about this issue. We'll get this taken care of this week.
