### ISSUE TITLE
Resolve-DnsName : catalog-patrickg.database.windows.net : DNS name does not exist

### ISSUE THREAD

**Issue by AzureArchitecture** [Microsoft/WingtipTicketsSaaS-DbPerTenant#12]
It looks like there is an issue in  .\Learning Modules\Common\CatalogAndDatabaseManagement.psm1:987 char:34 The path is returning catalog-patrickg.database.windows.net when it should be returning catalog-dpt-patrickg.database.windows.net 

I got this error running Demo-LoadGenerator.ps1

**Comment by AzureArchitecture** [comment]
Any news on this? I am about to start cracking code! :)

**Comment by AyoOlubeko** [comment]
Thanks for the ping. 
From the error you received, it looks like you're using the PowerShell scripts from the 'release-DR-georestore' branch and a Wingtip deployment from the 'master' branch.

The quickest solution would be to download the PowerShell scripts from the 'master' branch and use them against your existing deployment.

**More context**: 
The 'release-DR-georestore' branch is an experimental branch we have setup to test out DR tutorials for the WingtipTickets SaaS app. It includes additions to the Wingtip app (like DNS aliases) that are used during the disaster recovery tutorial. To use these scripts, you would need to use a different ARM deployment that can be found here: https://aka.ms/deploywingtipdpt-aliases. This link is also available in the readme for the branch.
