### ISSUE TITLE
Demo-ProvisionAndCatalog.ps1 Fails

### ISSUE THREAD

**Issue by pkandra** [Microsoft/WingtipTicketsSaaS-DbPerTenant#17]
This Powershell file fails looking for a Resolve-DnsName cmdlet in Get-ServerNameFromAlias on line 41:
$serverName = Get-ServerNameFromAlias $newTenantAlias

That cmdlet is also used in several other Powershell files and will probably fail there.
Here's the exact error message:

Get-ServerNameFromAlias : The term 'Resolve-DnsName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At C:\Users\pkandra.ATLANTA\Downloads\WingtipTicketsSaaS-DbPerTenant-master\WingtipTicketsSaaS-DbPerTenant-master\Learning Modules\Provision and Catalog\Demo-ProvisionAndCatalog.ps1:41 
char:19
+     $serverName = Get-ServerNameFromAlias $newTenantAlias
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Resolve-DnsName:String) [Get-ServerNameFromAlias], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-ServerNameFromAlias

**Comment by AyoOlubeko** [comment]
Hi there - do you know which version of PowerShell you have installed on your machine? The Resolve-DnsName cmdlet should be available by default in PowerShell 4.0 and beyond

**Comment by pkandra** [comment]
That's probably it then...I have version 3.  Thank you!

PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      -1     -1

**Comment by rajat28negi** [comment]
I am getting the same problem and powershell is of latest version i.e 5.1
